import {t,getDateLocale} from './i18n';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,CircleAlert,Copy,Globe2,LoaderCircle,MoreHorizontal,Play,Plus,RefreshCw,RotateCcw,Search,ShieldCheck,Square,Trash2,Wifi,X} from 'lucide-react';
import {defaults,normalizePreferences,listProfiles,saveProfile,parseProxyUri,startProfile,closeProfile,restartProfile,deleteProfile,restoreProfile,testProxy,matchRegion,validateDraft,type IpRegion,type BrowserProfile,type ProfileDraft,type ProxyMode,type ProxyTest} from './browser-profiles';
import {native,openFirefoxDownload} from './bridge';
import {ProfileAdvanced,ProfilePreview} from './ProfileAdvanced';
import BrowserIcon from './BrowserIcon';
const browsers={chrome:'Chrome',edge:'Edge',firefox:'Firefox'};
const proxyLabel=(p:BrowserProfile)=>p.proxy.mode==='system'?'系统代理':p.proxy.mode==='direct'?'直连':`${p.proxy.mode.toUpperCase()} · ${p.proxy.host}:${p.proxy.port}`;
function draftFor(p:BrowserProfile):ProfileDraft {return {name:p.name,browser:p.browser,notes:p.notes,tags:[...p.tags],proxy:{...p.proxy},preferences:normalizePreferences(p.preferences),password:'',clearPassword:false};}
export default function BrowserProfiles({onSelect,busy,onBusyChange,initialEditId,onEditConsumed}:{onSelect:(p:BrowserProfile,history?:boolean)=>void;busy:boolean;onBusyChange:(value:boolean)=>void;initialEditId?:string|null;onEditConsumed:()=>void}) {
  const [profiles,setProfiles]=useState<BrowserProfile[]>([]),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[trash,setTrash]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[notice,setNotice]=useState('');
  const [editor,setEditor]=useState<{id?:string;copyId?:string;hasPassword?:boolean;running?:boolean}|null>(null),[draft,setDraft]=useState<ProfileDraft>(defaults),[tagsInput,setTagsInput]=useState(''),[uri,setUri]=useState(''),[test,setTest]=useState<ProxyTest|null>(null),[section,setSection]=useState<'basic'|'proxy'|'advanced'>('basic');
  const [regionMatch,setRegionMatch]=useState<IpRegion|null>(null);
  useEffect(()=>{setRegionMatch(null);},[editor,draft.browser,draft.proxy.mode,draft.proxy.host,draft.proxy.port,draft.proxy.username,draft.password,draft.clearPassword]);
  const [confirmation,setConfirmation]=useState<{p:BrowserProfile;kind:'close'|'restart'|'delete'|'purge'}|null>(null),[menu,setMenu]=useState<string|null>(null),[menuPosition,setMenuPosition]=useState({top:0,right:0});
  const dialog=useRef<HTMLDialogElement>(null),confirmDialog=useRef<HTMLDialogElement>(null),inFlight=useRef(false),alive=useRef(true);
  async function load(){if(inFlight.current)return;inFlight.current=true;try{const next=await listProfiles();if(alive.current){setProfiles(next);setError('');}}catch(e){if(alive.current)setError(String(e));}finally{inFlight.current=false;if(alive.current)setLoading(false);}}
  useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>{if(!inFlight.current)void load();},6000);return()=>{alive.current=false;clearInterval(timer);};},[]);
  useEffect(()=>{const outside=(e:PointerEvent)=>{if(!(e.target as HTMLElement).closest('.profile-more'))setMenu(null);};const close=()=>setMenu(null);document.addEventListener('pointerdown',outside);window.addEventListener('resize',close);window.addEventListener('scroll',close,true);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',close);window.removeEventListener('scroll',close,true);};},[]);
  useEffect(()=>{if(editor){dialog.current?.showModal();dialog.current?.querySelector<HTMLInputElement>('input')?.focus();}else dialog.current?.close();},[editor]);
  useEffect(()=>{if(confirmation)confirmDialog.current?.showModal();else confirmDialog.current?.close();},[confirmation]);
  useEffect(()=>{if(initialEditId&&profiles.length){const p=profiles.find(p=>p.id===initialEditId);if(p)edit(p);onEditConsumed();}},[initialEditId,profiles]);
  async function action(callback:()=>Promise<void>){if(working||busy)return;setWorking(true);onBusyChange(true);setError('');setNotice('');try{await callback();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking(false);onBusyChange(false);}}
  function edit(p:BrowserProfile,copy=false){setTagsInput(p.tags.join(', '));setDraft({...draftFor(p),name:copy?`${p.name} 副本`:p.name});setEditor(copy?{copyId:p.id,hasPassword:p.hasPassword}:{id:p.id,hasPassword:p.hasPassword,running:p.running});setTest(null);setError('');setUri('');setSection('basic');setMenu(null);}
  function create(){setTagsInput('');setDraft(defaults());setEditor({});setTest(null);setError('');setUri('');setSection('basic');}
  async function save(start:boolean){const issue=validateDraft(draft);if(issue){setError(issue);return;}await action(async()=>{const p=await saveProfile(draft,editor?.id,editor?.copyId);setEditor(null);setDraft(defaults());if(start)await startProfile(p.id);setNotice(editor?.running?'设置已保存，关闭并重新启动副本后生效。':native?'副本设置已保存。':'演示副本已保存，电脑没有改变。');});}
  async function confirm(){if(!confirmation)return;const {p,kind}=confirmation;await action(async()=>{if(kind==='close')await closeProfile(p.id);else if(kind==='restart')await restartProfile(p.id);else await deleteProfile(p.id,kind==='purge');setConfirmation(null);setNotice(kind==='delete'?'已移至最近删除，登录数据保留。':kind==='purge'?'副本数据已彻底删除。':kind==='restart'?'已按最新设置重新启动。':'副本已关闭。');});}
  const custom=['http','https','socks5'].includes(draft.proxy.mode),disabled=working||busy;
  const filtered=profiles.filter(p=>Boolean(p.deletedAt)===trash&&(!tag||p.tags.includes(tag))&&`${p.name} ${p.notes} ${p.tags.join(' ')} ${p.proxy.host}`.toLowerCase().includes(query.toLowerCase()));
  const tags=[...new Set(profiles.filter(p=>!p.deletedAt).flatMap(p=>p.tags))];
  const active=profiles.filter(p=>!p.deletedAt),running=active.filter(p=>p.running).length;
  return <div className="profiles-workspace">
    <section className="profile-intro"><div><span className="eyebrow">ISOLATED BY DESIGN</span><h2>{t("每个用途，一个独立空间。")}</h2><p>{t("独立登录、独立配置、独立代理。为不同用途创建浏览器副本。")}</p></div><img className="profile-ghost" src="/brand/symbol-primary.svg" alt="" /><div className="profile-metrics"><span><strong>{active.length}</strong>{t("个副本")}</span><span><strong>{running}</strong>{t("个运行中")}</span></div></section>
    <div className="profile-toolbar"><div className="profile-search"><Search size={16}/><input aria-label={t("搜索浏览器副本")} placeholder={t("搜索名称、标签或代理地址")} value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label={t("筛选标签")} value={tag} onChange={e=>setTag(e.target.value)}><option value="">{t("全部标签")}</option>{tags.map(tag=><option key={tag}>{tag}</option>)}</select><button className={`button ${trash?'primary':'secondary'}`} disabled={disabled} onClick={()=>{setTrash(!trash);setMenu(null);}}><Trash2 size={15}/>{t(trash?'返回副本':'最近删除')}</button><button className="button primary" disabled={disabled} onClick={create}><Plus size={16}/>{t("新建副本")}</button></div>
    {t(error&&!editor&&<div className="notice warning-notice" role="alert"><CircleAlert size={17}/><p>{t(error)}</p></div>)}{t(notice&&<div className="profile-notice" role="status"><Check size={15}/>{t(notice)}</div>)}
    <section className="profile-table-card"><div className="profile-table-heading"><h3>{t(trash?'最近删除':'浏览器副本')}<span>{filtered.length}</span></h3><button className="icon-button" aria-label={t("刷新副本列表")} disabled={disabled||loading} onClick={()=>void load()}><RefreshCw size={16} className={loading?'spin':''}/></button></div>
    <div className="profile-table-scroll"><table className="profile-table"><thead><tr><th>{t("名称与浏览器")}</th><th>{t("代理")}</th><th>{t("检测服务出口")}</th><th>{t("状态")}</th><th>{t("操作")}</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}>
      <td><button className="profile-name-button" disabled={disabled||trash} onClick={()=>onSelect(p)}><BrowserIcon browser={p.browser}/><span><strong>{p.name}</strong><small>{t(browsers[p.browser])}{p.notes?` · ${p.notes.slice(0,30)}`:''}</small></span></button><div className="profile-tags">{p.tags.map(tag=><span key={tag}>{tag}</span>)}</div></td>
      <td><span className="profile-proxy">{t(proxyLabel(p))}</span>{t(p.proxy.username&&<small className="profile-muted">{t("带认证 ·")}{t(p.hasPassword?'密码已保存':'未保存密码')}</small>)}{p.pendingRestart&&<small className="profile-pending">{t("新设置待重启")}</small>}</td>
      <td><strong className="profile-ip">{t(p.lastTest?.ip||'尚未检测')}</strong><small className="profile-muted">{t(p.lastTest?`${p.lastTest.country||'地区未知'} · ${p.lastTest.latency} ms · ${new Date(p.lastTest.checkedAt).toLocaleString(getDateLocale())}`:'在当前代理路径测试出口')}</small></td>
      <td><span className={`profile-state ${p.running?'running':''}`}><i/>{t(trash?'已删除':!p.browserAvailable?'浏览器未安装':p.running?'运行中':'已关闭')}</span>{t(p.regionalError&&<small className="profile-pending">{t(p.regionalError)}</small>)}{p.running&&p.regionalReady===false&&<small className="profile-pending">{t("区域接口未就绪，请重启")}</small>}{p.running&&!p.proxyReady&&<small className="profile-pending">{t("代理未就绪，请检查凭据并重启")}</small>}</td>
      <td><div className="profile-actions">{trash?<><button className="button secondary compact" disabled={disabled} onClick={()=>void action(async()=>{await restoreProfile(p.id);setNotice('副本已恢复，登录数据保留。');})}><RotateCcw size={14}/>{t("恢复")}</button><button className="icon-button danger" disabled={disabled} aria-label={t(`彻底删除 ${p.name}`)} onClick={()=>setConfirmation({p,kind:'purge'})}><Trash2 size={16}/></button></>:<><button className="button secondary compact" disabled={disabled||!p.browserAvailable} onClick={()=>void action(()=>startProfile(p.id))}>{p.running?<ArrowRight size={14}/>:<Play size={14}/>} {t(p.running?'打开窗口':'启动')}</button><div className="profile-more"><button className="icon-button" disabled={disabled} aria-label={t(`${p.name} 更多操作`)} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();setMenuPosition({top:Math.max(10,Math.min(rect.bottom+4,window.innerHeight-340)),right:window.innerWidth-rect.right});setMenu(menu===p.id?null:p.id);}}><MoreHorizontal size={18}/></button>{menu===p.id&&<div className="profile-menu" style={menuPosition}><button onClick={()=>onSelect(p)}>{t("环境检测")}</button><button onClick={()=>edit(p)}>{t("编辑设置")}</button><button onClick={()=>edit(p,true)}><Copy size={13}/>{t("复制配置")}</button><button onClick={()=>void action(async()=>{const result=await testProxy(undefined,p.id);setNotice(`${p.name}：${result.ip||'未取得 IP'} · ${result.country||'未知地区'} · ${result.target}`);setMenu(null);})}><Wifi size={13}/>{t("测试代理")}</button><button onClick={()=>onSelect(p,true)}>{t("修复记录")}</button>{!p.browserAvailable&&p.browser==='firefox'&&<button onClick={()=>void openFirefoxDownload()}>{t("下载 Firefox")}</button>}{p.running&&<><button onClick={()=>{setMenu(null);setConfirmation({p,kind:'restart'});}}>{t("重启副本")}</button><button onClick={()=>{setMenu(null);setConfirmation({p,kind:'close'});}}><Square size={13}/>{t("关闭副本")}</button></>}<button className="danger" disabled={p.running} onClick={()=>{setMenu(null);setConfirmation({p,kind:'delete'});}}>{t("移至最近删除")}</button></div>}</div></>}</div></td>
    </tr>)}</tbody></table></div>{!filtered.length&&<div className="profile-empty"><Globe2 size={32}/><h3>{t(loading?'正在读取副本…':trash?'最近删除为空':'没有找到副本')}</h3><p>{t(trash?'删除的副本会保留在这里，支持恢复。':'新建一个浏览器副本，或调整搜索条件。')}</p></div>}</section>
    <p className="profile-footnote"><ShieldCheck size={14}/>{t("关闭主窗口后，运行中的副本和代理会继续在后台工作。真正退出请使用“偏好设置 → 退出应用”。")}</p>
    <dialog ref={dialog} className="app-dialog profile-editor" onCancel={e=>{e.preventDefault();if(!disabled)setEditor(null);}}><button className="modal-close" aria-label={t("关闭副本设置")} disabled={disabled} onClick={()=>setEditor(null)}><X size={19}/></button><span className="eyebrow">BROWSER PROFILE</span><h2>{t(editor?.id?'编辑副本':editor?.copyId?'复制配置，新建副本':'创建浏览器副本')}</h2><p className="modal-subtitle">{t(editor?.running?'当前副本正在运行，修改的代理和环境设置在下次启动时生效。':editor?.copyId?'复制浏览器设置与代理配置；新副本拥有独立的登录数据。':'给这个空间起个名字，再选择它的网络连接方式。')}</p>
    <div className="profile-editor-layout"><div className="profile-editor-main"><nav className="profile-editor-tabs" aria-label={t("副本设置分类")}>{([['basic','基础设置'],['proxy','代理设置'],['advanced','高级设置']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={section===id} className={section===id?'selected':''} disabled={disabled} onClick={()=>setSection(id)}>{t(label)}</button>)}</nav>
    <fieldset className="profile-fields" disabled={disabled}>{section==='basic'&&<div className="profile-form"><label>{t("副本名称")}<input autoFocus maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder={t("例如：日常使用 / 工作环境")}/></label><label>{t("浏览器")}<select disabled={Boolean(editor?.id)||disabled} value={draft.browser} onChange={e=>{const browser=e.target.value as ProfileDraft['browser'];setDraft({...draft,browser,preferences:{...draft.preferences,fontRestriction:browser==='firefox'&&draft.preferences.fontRestriction,advanced:{...draft.preferences.advanced,blockWebgl:browser==='firefox'&&draft.preferences.advanced.blockWebgl,resistFingerprinting:browser==='firefox'&&draft.preferences.advanced.resistFingerprinting}}});}}>{Object.entries(browsers).map(([id,name])=><option key={id} value={id}>{t(name)}</option>)}</select></label><label>{t("标签")}<span className="profile-field-hint">{t("用逗号分隔")}</span><input value={tagsInput} onChange={e=>{setTagsInput(e.target.value);setDraft({...draft,tags:[...new Set(e.target.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean))]});}} placeholder={t("工作, 日常")}/></label><label>{t("备注")}<input maxLength={1000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder={t("可选，记录用途")}/></label></div>}
    {section==='proxy'&&<div className="profile-form-section"><h3><Wifi size={17}/>{t("代理设置")}</h3><div className="proxy-modes">{([['system','系统代理'],['direct','直连'],['http','HTTP'],['https','HTTPS'],['socks5','SOCKS5']] as [ProxyMode,string][]).map(([mode,label])=><button key={mode} aria-pressed={draft.proxy.mode===mode} className={draft.proxy.mode===mode?'selected':''} disabled={disabled} onClick={()=>{setDraft({...draft,proxy:{...draft.proxy,mode}});setTest(null);}}>{t(label)}</button>)}</div>
    {custom?<><div className="proxy-paste"><input aria-label={t("粘贴代理链接")} value={uri} onChange={e=>setUri(e.target.value)} placeholder={t("粘贴代理链接，自动填写地址和认证")}/><button className="button secondary compact" disabled={disabled||!uri} onClick={()=>{try{const next=parseProxyUri(uri);setDraft({...draft,...next,clearPassword:false});setUri('');setError('');setTest(null);}catch(e){setError(String(e));}}}>{t("识别")}</button></div><div className="profile-form"><label>{t("代理地址")}<input value={draft.proxy.host} onChange={e=>{setDraft({...draft,proxy:{...draft.proxy,host:e.target.value}});setTest(null);}} placeholder={t("127.0.0.1 或 proxy.example.com")}/></label><label>{t("端口")}<input type="number" min={1} max={65535} value={draft.proxy.port||''} onChange={e=>{setDraft({...draft,proxy:{...draft.proxy,port:Number(e.target.value)}});setTest(null);}}/></label><label>{t("用户名")}<input autoComplete="off" value={draft.proxy.username} onChange={e=>{setDraft({...draft,proxy:{...draft.proxy,username:e.target.value}});setTest(null);}} placeholder={t("无认证时留空")}/></label><label>{t("密码")}<input type="password" autoComplete="new-password" value={draft.password||''} onChange={e=>{setDraft({...draft,password:e.target.value,clearPassword:false});setTest(null);}} placeholder={t(editor?.hasPassword?'已安全保存；留空保留原密码':'无认证时留空')}/></label></div>{editor?.hasPassword&&<label className="profile-checkbox"><input type="checkbox" checked={draft.clearPassword} onChange={e=>setDraft({...draft,clearPassword:e.target.checked,password:''})}/>{t("清除已保存的密码")}</label>}<p className="profile-field-hint">{t("密码存入系统凭据存储。代理失效时，该副本网页请求不会自动改为直连。")}</p></>:<p className="profile-field-hint">{t(draft.proxy.mode==='direct'?'此副本明确使用直连，不继承系统代理。VPN / TUN 的路由仍由系统决定。':'此副本使用浏览器支持的系统网络配置。代理测试结果需要在浏览器内复检。')}</p>}
    <div className="proxy-test-row"><button className="button secondary compact" disabled={disabled} onClick={()=>void action(async()=>{setTest(null);const result=await testProxy({...draft,name:draft.name||'代理测试'},editor?.id||editor?.copyId);setTest(result);})}>{working?<LoaderCircle size={14} className="spin"/>:<Wifi size={14}/>}{t("测试连接")}</button>{test&&<span role="status">{t(test.ip||'未获取 IP')} · {t(test.country||'地区未知')} · {test.latency} ms{t(!native&&'（演示）')}</span>}</div>{test&&<p className="profile-field-hint">{t(test.target)}。{t(test.connection)}</p>}{test?.clock&&<p className="profile-field-hint" role="status">{t(test.clock.value)}。{t(test.clock.detail)}</p>}</div>}
    {section==='advanced'&&<ProfileAdvanced draft={draft} onChange={setDraft} match={regionMatch} matching={working} onMatch={()=>void action(async()=>{setRegionMatch(null);setRegionMatch(await matchRegion({...draft,name:draft.name||'区域预览'},editor?.id||editor?.copyId));})}/>}
    </fieldset></div><ProfilePreview draft={draft} running={editor?.running} match={regionMatch}/></div>{t(error&&<p className="profile-error" role="alert">{t(error)}</p>)}<div className="modal-actions"><button className="button secondary" disabled={disabled} onClick={()=>setEditor(null)}>{t("取消")}</button><button className="button secondary" disabled={disabled} onClick={()=>void save(false)}>{working?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}{t("保存")}{t(editor?.running?'，下次启动生效':'')}</button>{!editor?.running&&<button className="button primary" disabled={disabled} onClick={()=>void save(true)}><Play size={15}/>{t(editor?.id?'保存并启动':'创建并启动')}</button>}</div></dialog>
    <dialog ref={confirmDialog} className="app-dialog" onCancel={e=>{e.preventDefault();if(!disabled)setConfirmation(null);}}><span className="modal-feature"><CircleAlert size={25}/></span><h2>{t(confirmation?.kind==='purge'?'彻底删除副本？':confirmation?.kind==='delete'?'移至最近删除？':confirmation?.kind==='restart'?'重新启动这个副本？':'关闭这个副本？')}</h2><p className="modal-subtitle">{confirmation?.p.name}</p><div className="notice"><CircleAlert size={17}/><p>{t(confirmation?.kind==='purge'?'登录状态、缓存、设置、修复记录及保存的代理凭据将被清除，此操作无法恢复。':confirmation?.kind==='delete'?'数据保留在最近删除中，可随时恢复。':confirmation?.kind==='restart'?'请先保存未完成的输入。关闭后会使用最新代理与设置重新启动。':'请先保存未完成的输入。仅关闭这个副本，代理在浏览器退出后停止。')}</p></div>{t(error&&<p className="profile-error" role="alert">{t(error)}</p>)}<div className="modal-actions"><button className="button secondary" disabled={disabled} onClick={()=>setConfirmation(null)}>{t("取消")}</button><button className={`button ${confirmation?.kind==='purge'||confirmation?.kind==='delete'?'danger':'primary'}`} disabled={disabled} onClick={()=>void confirm()}>{working&&<LoaderCircle size={15} className="spin"/>}{t(confirmation?.kind==='purge'?'彻底删除':confirmation?.kind==='delete'?'移至最近删除':confirmation?.kind==='restart'?'保存后重启':'关闭副本')}</button></div></dialog>
  </div>;
}
