import {t} from './i18n';
import { useState } from 'react';
import { Check, CircleAlert, History, Info, RefreshCw, Type } from 'lucide-react';
import type { FontCatalog, FontOutcome } from './bridge';

export function FontReview({catalog,initialIds,busy,onClose,onSubmit}:{catalog:FontCatalog;initialIds:string[];busy:boolean;onClose:()=>void;onSubmit:(ids:string[],consent:boolean)=>void}) {
  const [selected,setSelected]=useState(initialIds.filter(id=>catalog.items.some(f=>f.id===id)));
  const [consent,setConsent]=useState(false);
  return <><span className="modal-feature partial"><Type size={26}/></span><span className="eyebrow">FONT MANAGEMENT</span><h2 id="modal-title">{t("选择可卸载的用户字体")}</h2><p className="modal-subtitle">{t("仅处理你主动选择的字体，文件与注册信息在卸载前备份。不会放入默认一键修复。")}</p><div className="notice warning-notice"><Info size={17}/><p>{t(catalog.note)}</p></div><h3 className="detail-heading">{t("可处理的用户字体 ·")}{catalog.items.length}</h3>{catalog.items.length ? <div className="repair-options">{catalog.items.map(font=><label key={font.id} className={`repair-option ${selected.includes(font.id)?'checked':''}`}><input type="checkbox" checked={selected.includes(font.id)} disabled={busy} onChange={e=>{setSelected(prev=>e.target.checked?[...prev,font.id]:prev.filter(id=>id!==font.id));setConsent(false);}}/><span className="custom-checkbox">{selected.includes(font.id)&&<Check size={12}/>}</span><span><strong>{font.label}</strong><small>{font.fileName} · {t((font.bytes/1048576).toFixed(1))} MiB</small></span></label>)}</div>:<div className="font-empty">{t("没有找到可自动处理的用户字体。网页检测到的字体可能来自系统、所有用户安装、字体组件或网页字体。")}</div>}<h3 className="detail-heading">{t("系统目录中的字体 · 保留")}</h3><div className="protected-fonts">{catalog.protected.length?catalog.protected.map(name=><span key={name}>{t(name)}</span>):<span>{t("常见系统目录未命中；这不是完整的字体安装列表。")}</span>}</div><p className="font-scope-note">{t("微软雅黑、宋体等系统字体仍可能被 Chrome / Edge 识别。卸载用户字体不会隐藏系统字体，也不会将检测结果伪造为通过。")}</p>{catalog.items.length>0&&<label className="timezone-consent"><input type="checkbox" checked={consent} disabled={busy||!selected.length} onChange={e=>setConsent(e.target.checked)}/><span>{t("我确认卸载所选")}{selected.length} {t("个用户字体，了解这会影响当前用户所有应用的显示。已保存相关工作并退出专用浏览器；备份保留在本机，可从修复记录恢复。")}</span></label>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={onClose}>{t("取消")}</button><button className="button primary" disabled={busy||!selected.length||!consent} onClick={()=>onSubmit(selected,consent)}><Type size={15}/>{t(busy?'正在备份与处理':`备份并卸载 ${selected.length} 个字体`)}</button></div></>;
}
export function fontResultSummary(outcomes:FontOutcome[]) {return {completed:outcomes.filter(o=>o.success).length,failed:outcomes.filter(o=>!o.success).map(o=>o.id)};}
export function FontResult({outcomes,busy,onHistory,onRetry}:{outcomes:FontOutcome[];busy:boolean;onHistory:()=>void;onRetry:(ids:string[])=>void}) {
  const {completed,failed}=fontResultSummary(outcomes);
  return <><span className={`modal-feature ${failed.length?'partial':'success'}`}><CircleAlert size={26}/></span><span className="eyebrow">FONT OPERATIONS</span><h2 id="modal-title">{t(completed?`已卸载 ${completed} 个用户字体`:'本次未完成字体卸载')}</h2><p className="modal-subtitle">{t(failed.length?`${failed.length} 个未完成。`:'')}{t("系统字体保留。卸载结果不等于网页字体检测已通过，请完全退出浏览器后复检；仍可见时可能需要注销或重启。")}</p><div className="result-list">{outcomes.map(o=><div key={o.id} className={o.success?'completed':'incomplete'}>{o.success?<Check className="success-icon" size={18}/>:<Info className="warning-icon" size={18}/>}<span><strong>{o.label}<em className="result-item-status">{t(o.success?'已卸载':'未完成')}</em></strong><small>{t(o.message)}</small></span></div>)}</div><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={onHistory}><History size={15}/>{t("查看备份与恢复")}</button>{failed.length>0&&<button className="button primary" disabled={busy} onClick={()=>onRetry(failed)}><RefreshCw size={15}/>{t("重选未完成字体")}</button>}</div></>;
}
